### ISSUE TITLE
Adjustments in properties

### ISSUE THREAD

**Issue by aazocar** [ISE-FIZKarlsruhe/nfdicore#14]
* The domain of nfdico:subjectArea should also include nfdico:Person
* The domain of nfdicore:emailAddress data property should also have nfdico:Person
* nfdico:instance term is not clear, the description does not match the domain and range of the property. Domain and range are nfdico:Service although it is a relationship between an RDM Tool to its running instance. (Before this property was used with nfdico:RDMTool and nfdico:InstanceOfRDMTool)
* The domain and range of nfdico:sparqlEndpoint is nfdico:Resource. Does this mean that a publication could be a sparqlEndpoint of another?	SparqlEndpoint class is expected in the range.
* nfdicore:provisionType usage is not clear. Range should be the type of provision?

**Comment by SashaVsesviatska** [comment]
- updated 1 and 2
- updated the definition of nfdicore:instance
- yes, following the discussion on 16.12 any sparql endpoint is a resource (earlier Work). It was agreed to remove the class due to the lack of the use case, see https://docs.google.com/presentation/d/1qv-ftgccmSWGdxGPLtNRL9UlYbGCng_H/edit#slide=id.g1afcf9e57f2_7_34 . 
- yes, range will be the type of a provision e.g. schema:Intangible, schema:CreativeWork or their subclasses. more on the usage of provisionType https://docs.google.com/presentation/d/1qv-ftgccmSWGdxGPLtNRL9UlYbGCng_H/edit#slide=id.g1afcf9e57f2_0_0

**Comment by SashaVsesviatska** [comment]
The range of :provisionType is a resource, e.g. schema:Service. 
```

:service01 rdf:type nfdicore:ProvidedResource ;
                  nfdicore:provisionType schema:Service . 
```

I hope it helps!

**Comment by joergwa** [comment]
Is nfdicore:provisionType intended to be a subprop of rdf:type? If so, do we really need it?   @SashaVsesviatska

**Comment by SashaVsesviatska** [comment]
It is not intended to be a subproperty of rdf:type, according to the slides and discussion during the workshop. Answering to Said's remark: why is it in not correct? a class is an instance itself, see RDF documentation:

- "rdfs:range is an instance of [rdf:Property](https://www.w3.org/TR/rdf-schema/#ch_property) that is used to state that the values of a property are instances of one or more classes." 

--> "This is the class of resources that are RDF classes. rdfs:Class is an instance of rdfs:Class."
--> "A class may be a member of its own class extension and may be an instance of itself."

**Comment by joergwa** [comment]
Is it intended that class `schema:Service` is a `Resource` ?

**Comment by joergwa** [comment]
After discussion, we decide to remove this property from the ontlogy. Alternatively one might simply use rdf:type.
