### ISSUE TITLE
MediaType

### ISSUE THREAD

**Issue by aazocar** [ISE-FIZKarlsruhe/nfdicore#15]
The description of nfdico:MediaType is not clear. The examples are file extensions, in the comment it refers to the file format... but media type could be something like the [MIME type](https://www.iana.org/assignments/media-types/media-types.xhtml) as well. Is it something specific or is this an umbrella class for all these mentioned ?

**Comment by SashaVsesviatska** [comment]
It is a general class, in case you need more specific classes, please introduce them in matwerk ontology.

**Comment by SashaVsesviatska** [comment]
Hi, according to the definition, media type and object type do not have subclass-superclass relation, since object type defines the type of an object in a data collection, e.g. photograph, and media type is a specific file format, e.g. tiff. 

MediaType is equivalent to the dcterms:MediaType, defined as "A file format or physical medium.", so I do not think we need to create more confusion and define FileFormat and link it to dcterms:MediaType. 

I would leave the issue open for more discussion and brainstorming for others!

**Comment by joergwa** [comment]
What is the actual purpose of this information? 

- To support a developer to render some content (image, video, text, etc.) properly in a website"?  
- Support someone who is looking for "videos", "images" or "text-documents" in the dataset?   
- Deliver the right content type on HTTP requests?
- ... ?

Again, what is the indended use of "nfdicore:MediaType" ?

**Comment by SashaVsesviatska** [comment]
To support the search of specific object types in specific formats. MediaType is superclass of FileFormat in dcterms. it basically, additionally to file formats, allows to provide physical description information for an item in a collection, which may be useful in culture domain.

**Comment by hofmannv** [comment]
Hm, .. 

I think we have a bit of a confusion here. Generally (at least i think) a "type" of something is different from the "format" of something:
- A "type" refers to the content of a thing (i.e. is it spacial data (image, geo-data, etc) or a time-series (audio, voltage recording) or something else (e.g. force curve from tensile-test)). 
- A "format" is about how something is encoded (in the digital world). (.jpg; .mat, .whatever). 

Thinking on a broad scale (i.e. core ontology), "Media(-files)" should probably be some specific subclass of "files". And what the core ontology would need is a definition of Format and Type for the more general class (i.e. looking for media might actually be more culture specific, whereas in Material Science people search for data types or data formats (which would probably also be some kind of "files" (or some other named or already existing useful superclass). 

Not sure if the subclass hierarchy of dct:MediatypeOrExtend makes really sense, because there is some correlation between formats and types, but no strict causal relationship (i.e. i can save pictures in many different formats .jpg, .svg, .raw etc..)

In my eyes the core ontology would benefit from using e.g.
- [cdt:Format](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/format/) to define a format (i.e. also for any type of [files](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#FileFormat) 
and 
- [dct:type](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/type/) to define a type (note also that the comment points to the use of format. 
As properties on a general level. Things like "Media-files" should then inherit these properties through the hierarchy. 

That would then also allow 
> To support the search of specific object types in specific formats.

I would be curious what you think...

**Comment by joergwa** [comment]
@hofmannv 
>     A "type" refers to the content of a thing (i.e. is it spacial data (image, geo-data, etc) or a time-series (audio, voltage recording) or something else (e.g. force curve from tensile-test)).
>     A "format" is about how something is encoded (in the digital world). (.jpg; .mat, .whatever).

dct:FileFormat might fit the second case ("format")  E.g. a MIME-Type 
(also dct:MediaType might fit, because it is a superclass of dct:FileFormat.) 
(then, also nfdi:MediaType fits because it is equiv to dct:MediaType)


For the first case ("type"), I understand that you are referring to some specific (materials) science related types of content.  This does not fit the definition of dct:MediaType ("A file format or physical medium.").
Here we need something else. Is there some controlled vocabulary?


@aazocar 
In the ontology nfdi:MediaType (equiv to dct:MediaType) refers to "A digital resource format or physical medium.": I adapted the description and added some more examples. I also introduced a MIME-Type class below nfdi:MediaType.

**Comment by joergwa** [comment]
What do you suggest as domain for the DP `fileExtension`?

**Comment by joergwa** [comment]
OK. added.

**Comment by joergwa** [comment]
@saidfathalla 
One more question about the `fileExtension` property 
In the Culture Graph I found (most) media types are used together with Wikidata. See [here](https://nfdi4culture.de/resources/knowledge-graph.html#query=PREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%20WHERE%20%7B%0A%20%20%3Fsth%20%3Chttps%3A%2F%2Fnfdi4culture.de%2Fontology%23mediaType%3E%20%3Fmt%20.%0A%20%20%3Fmt%20%3Fpred%20%3Chttps%3A%2F%2Fnfdi4culture.de%2Fontology%23MediaType%3E%20.%0A%20%20%3Fmt%20owl%3AsameAs%20%3Fsame%20.%0A%7D%20LIMIT%2010&endpoint=https%3A%2F%2Fnfdi4culture.de%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)
 
How do you plan to use `fileExtension` as DP ? 

Would you mind to suggest a description for the DP and how it differs from the `mediaType` property in usage. So that users better understand when to use which?

**Comment by joergwa** [comment]
Thank You!
