### ISSUE TITLE
Conflicts with schema.org classes

### ISSUE THREAD

**Issue by saidfathalla** [ISE-FIZKarlsruhe/nfdicore#22]
Classes that already exist in schema.org are imported into a different place in the hierarchy. For example, in nfdicore, schema:Website, schema:Collection, schema:SoftwareSourceCode are subclasses of schema:Product,  but they are subclasses of schema:CreativeWork	in schema.org.

**Comment by SashaVsesviatska** [comment]
Hi, thank you!

- there is no schema:Website and schema:SoftwareSourceCode in the nfdicore ontology, we mapped nfdicore:Website and nfdicore:Software to other ontologies due to more fitting defintions. Tzank you for pointing out the collection issue. 

I will change the super class of all of the three classes to nfdicore:Resource, so we are more flexible!
