### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by lsoehn** [ISE-FIZKarlsruhe/nfdicore#51]
In former versions of the NFDIcore there was a mappings.ttl with various mappings to external vocabularies. For example, nfdicore:Organization was mapped to schema:Organization, nfdicore:Person to schema:Person, nfdicore:Software to sd:Software, etc. Are those mappings no longer possible, are they made in another way or am I blind? I can't find them in nfdicore.ttl.

**Comment by joergwa** [comment]
Thank you for your feedback.
We removed the mappings due to insufficient testing.
In the latest version of the ontology, we have integrated BFO as the top-level ontology to leverage reasoning capabilities extensively.
The previous mappings introduced inconsistencies with the new version. Using "equivalentClass" requires ensuring seamless integration of hierarchy, definitions, and axioms between both ontologies. Unfortunately, the majority of the ontologies in the old mappings did not meet this criterion.
If you still require the mappings, you are welcome to use the old file and validate them independently. We would greatly appreciate it if you could share your findings with us.
